# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['../main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('snipercat.png', '.'),
        ('snipercat.ico', '.'),
    ],
    hiddenimports=[
        'PyQt6.QtSvg',
        'PyQt6.QtSvgWidgets',
        'PyQt6.QtNetwork',
        'pynput.keyboard',
        'pynput.mouse',
        'PIL.Image',
        'PIL.ImageGrab',
        'PIL.ImageOps',
        'websockets.legacy.client',
        'websockets.legacy.server',
        'websockets.sync.client',
        'win11toast',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'cv2',
        'opencv_python',
        'numpy',
        'scipy',
        'pandas',
        'matplotlib',
        'sklearn',
        'skimage',
        'scikit_learn',
        'torch',
        'torchvision',
        'torchaudio',
        'tensorflow',
        'keras',
        'jax',
        'jaxlib',
        'numba',
        'sympy',
        'imageio',
        'imageio_ffmpeg',
        'moviepy',
        'mediapipe',
        'albumentations',
        'tkinter',
        '_tkinter',
        'PyQt5',
        'PySide2',
        'PySide6',
        'wx',
        'kivy',
        'PyQt6.QtWebEngineCore',
        'PyQt6.QtWebEngineWidgets',
        'PyQt6.QtWebEngineQuick',
        'PyQt6.QtMultimedia',
        'PyQt6.QtMultimediaWidgets',
        'PyQt6.QtQuick',
        'PyQt6.QtQuickWidgets',
        'PyQt6.QtQml',
        'PyQt6.QtCharts',
        'PyQt6.QtDataVisualization',
        'PyQt6.Qt3DCore',
        'PyQt6.Qt3DRender',
        'PyQt6.Qt3DInput',
        'PyQt6.Qt3DExtras',
        'PyQt6.QtPdf',
        'PyQt6.QtPdfWidgets',
        'PyQt6.QtOpenGLWidgets',
        'autoit',
        'pytesseract',
        'easyocr',
        'paddleocr',
        'pywinauto',
        'pytest',
        'unittest',
        'IPython',
        'jupyter',
        'notebook',
        'setuptools._vendor',
    ],
    noarchive=False,
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher,
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='Sol Sniper V3.0.0 [BETA 7.1]',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='snipercat.ico',
    onefile=True,
)
