# -*- mode: python ; coding: utf-8 -*-

import os
import sys
import site
from pathlib import Path

block_cipher = None

a = Analysis(
    ['../main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('snipercat.png', '.'),
        ('snipercat.ico', '.'),
    ],
    hiddenimports=[
        'psutil',
        'keyboard',
        'pynput',
        'pynput.keyboard',
        'pynput.mouse',
        'pyautogui',
        'PyQt6.QtSvg',
        'PyQt6.QtSvgWidgets',
        'PyQt6.QtNetwork',
        'PyQt6.QtWebEngineCore',
        'PyQt6.QtWebEngineWidgets',
        'PyQt6.QtPrintSupport',
        'aiohttp',
        'asyncio',
        'configparser',
        'logging',
        're',
        'json',
        'time',
        'random',
        'requests',
        'threading',
        'subprocess',
        'platform',
        'webbrowser',
        'ctypes',
        'ctypes.wintypes',
        'datetime',
        'concurrent.futures',
        'win11toast',
        'discord.py-self',
        'PIL',
        'PIL.Image',
        'PIL.ImageGrab',
        'PIL.ImageOps',
        'pkg_resources',
        'pkg_resources.py2_warn',
        'PIL._tkinter_finder',
        'websockets',
        'websockets.legacy',
        'websockets.legacy.client',
        'websockets.legacy.server',
        'websockets.sync',
        'websockets.version',
        'multiprocessing',
        'queue',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'autoit',
        'autoit.*',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'tkinter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='Sol Sniper V3.0.0 [BETA 7]',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='snipercat.ico',
    version_info='version.txt',
    onefile=True
)